import { useEffect, useState } from 'react'
import { Building2, ExternalLink, MapPin, Phone, Play, Store } from 'lucide-react'
import { api, getEmbedVideoUrl, isDirectVideoUrl, resolveMediaUrl } from '../services/api'

type Company = { id: string; name: string; description: string; location: string; phone?: string; website?: string; image?: string; gallery?: string[]; video?: string; latitude?: number; longitude?: number; imageMotion?: 'float' | 'zoom' | 'none'; status: 'Open' | 'Coming soon' }
const directionsUrl = (company: Company) => company.latitude != null && company.longitude != null ? `https://www.google.com/maps/dir/?api=1&destination=${company.latitude},${company.longitude}` : `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(company.location)}`

export default function CompaniesPage() {
  const [companies, setCompanies] = useState<Company[]>([])
  const [loading, setLoading] = useState(true)
  useEffect(() => { api.get('/companies').then(({ data }) => setCompanies(data.companies || [])).finally(() => setLoading(false)) }, [])
  return <div className="min-h-screen overflow-hidden bg-stone-50 pt-4">
    <section className="relative isolate overflow-hidden bg-stone-950 px-4 py-20 text-white sm:px-6"><div className="pointer-events-none absolute -right-16 -top-20 h-80 w-80 rounded-full bg-red-500/30 blur-3xl animate-pulse" /><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[.24em] text-red-300">Hincton network</p><h1 className="mt-4 max-w-3xl text-4xl font-black tracking-tight sm:text-6xl">Our branches & companies.</h1><p className="mt-5 max-w-2xl text-lg text-stone-300">Live locations, stories, and services from the Hincton family.</p></div></section>
    <main className="mx-auto max-w-6xl px-4 py-12 sm:px-6">{loading ? <p className="text-stone-500">Loading locations…</p> : companies.length === 0 ? <div className="rounded-3xl border border-dashed border-stone-300 bg-white p-12 text-center"><Store className="mx-auto h-10 w-10 text-red-600" /><h2 className="mt-4 text-xl font-bold">More locations are on the way</h2></div> : <div className="grid gap-7 md:grid-cols-2">{companies.map((company) => { const media = company.image || company.gallery?.[0]; const motion = company.imageMotion === 'zoom' ? 'group-hover:scale-110' : company.imageMotion === 'float' ? 'group-hover:-translate-y-2' : ''; const embed = getEmbedVideoUrl(company.video); return <article key={company.id} className="group overflow-hidden rounded-3xl border border-stone-200 bg-white shadow-sm transition hover:shadow-xl hover:shadow-stone-900/10">{media && <div className="relative h-64 overflow-hidden bg-stone-200"><img src={resolveMediaUrl(media)} alt={company.name} className={`h-full w-full object-cover transition duration-700 ${motion}`} />{company.video && <span className="absolute bottom-4 right-4 flex h-10 w-10 items-center justify-center rounded-full bg-white/90 text-red-700 shadow"><Play className="ml-0.5 h-4 w-4 fill-current" /></span>}</div>}<div className="p-6"><div className="flex items-start justify-between gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-red-50 text-red-700"><Building2 className="h-5 w-5" /></span><span className={`rounded-full px-3 py-1 text-xs font-bold ${company.status === 'Open' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{company.status}</span></div><h2 className="mt-6 text-2xl font-extrabold text-stone-950">{company.name}</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-stone-600">{company.description}</p>{embed ? <iframe className="mt-5 aspect-video w-full rounded-2xl" src={embed} title={`${company.name} video`} allow="autoplay; fullscreen; picture-in-picture" allowFullScreen /> : company.video && isDirectVideoUrl(company.video) ? <video className="mt-5 aspect-video w-full rounded-2xl bg-black" src={resolveMediaUrl(company.video)} controls /> : null}<div className="mt-6 flex flex-wrap gap-3 border-t border-stone-100 pt-4 text-sm"><a target="_blank" rel="noreferrer" href={directionsUrl(company)} className="inline-flex items-center gap-2 font-bold text-red-700"><MapPin className="h-4 w-4" />Directions</a>{company.phone && <a href={`tel:${company.phone.replace(/\s/g, '')}`} className="inline-flex items-center gap-2 font-semibold text-stone-600"><Phone className="h-4 w-4 text-red-600" />{company.phone}</a>}{company.website && <a target="_blank" rel="noreferrer" href={company.website} className="inline-flex items-center gap-1 font-bold text-red-700">Website <ExternalLink className="h-4 w-4" /></a>}</div></div></article> } )}</div>}</main>
  </div>
}
