export interface PhoneCountry {
  name: string
  iso2: string
  dialCode: string
  minLength: number
  maxLength: number
}

export const phoneCountries: PhoneCountry[] = [
  { name: 'Afghanistan', iso2: 'AF', dialCode: '+93', minLength: 9, maxLength: 9 },
  { name: 'Albania', iso2: 'AL', dialCode: '+355', minLength: 8, maxLength: 9 },
  { name: 'Algeria', iso2: 'DZ', dialCode: '+213', minLength: 8, maxLength: 9 },
  { name: 'American Samoa', iso2: 'AS', dialCode: '+1684', minLength: 10, maxLength: 10 },
  { name: 'Andorra', iso2: 'AD', dialCode: '+376', minLength: 6, maxLength: 9 },
  { name: 'Angola', iso2: 'AO', dialCode: '+244', minLength: 9, maxLength: 9 },
  { name: 'Anguilla', iso2: 'AI', dialCode: '+1264', minLength: 10, maxLength: 10 },
  { name: 'Antigua and Barbuda', iso2: 'AG', dialCode: '+1268', minLength: 10, maxLength: 10 },
  { name: 'Argentina', iso2: 'AR', dialCode: '+54', minLength: 10, maxLength: 11 },
  { name: 'Armenia', iso2: 'AM', dialCode: '+374', minLength: 8, maxLength: 8 },
  { name: 'Aruba', iso2: 'AW', dialCode: '+297', minLength: 7, maxLength: 7 },
  { name: 'Australia', iso2: 'AU', dialCode: '+61', minLength: 9, maxLength: 9 },
  { name: 'Austria', iso2: 'AT', dialCode: '+43', minLength: 7, maxLength: 13 },
  { name: 'Azerbaijan', iso2: 'AZ', dialCode: '+994', minLength: 9, maxLength: 9 },
  { name: 'Bahamas', iso2: 'BS', dialCode: '+1242', minLength: 10, maxLength: 10 },
  { name: 'Bahrain', iso2: 'BH', dialCode: '+973', minLength: 8, maxLength: 8 },
  { name: 'Bangladesh', iso2: 'BD', dialCode: '+880', minLength: 10, maxLength: 10 },
  { name: 'Barbados', iso2: 'BB', dialCode: '+1246', minLength: 10, maxLength: 10 },
  { name: 'Belarus', iso2: 'BY', dialCode: '+375', minLength: 9, maxLength: 9 },
  { name: 'Belgium', iso2: 'BE', dialCode: '+32', minLength: 8, maxLength: 9 },
  { name: 'Belize', iso2: 'BZ', dialCode: '+501', minLength: 7, maxLength: 7 },
  { name: 'Benin', iso2: 'BJ', dialCode: '+229', minLength: 8, maxLength: 10 },
  { name: 'Bermuda', iso2: 'BM', dialCode: '+1441', minLength: 10, maxLength: 10 },
  { name: 'Bhutan', iso2: 'BT', dialCode: '+975', minLength: 7, maxLength: 8 },
  { name: 'Bolivia', iso2: 'BO', dialCode: '+591', minLength: 8, maxLength: 8 },
  { name: 'Bosnia and Herzegovina', iso2: 'BA', dialCode: '+387', minLength: 8, maxLength: 8 },
  { name: 'Botswana', iso2: 'BW', dialCode: '+267', minLength: 7, maxLength: 8 },
  { name: 'Brazil', iso2: 'BR', dialCode: '+55', minLength: 10, maxLength: 11 },
  { name: 'British Virgin Islands', iso2: 'VG', dialCode: '+1284', minLength: 10, maxLength: 10 },
  { name: 'Brunei', iso2: 'BN', dialCode: '+673', minLength: 7, maxLength: 7 },
  { name: 'Bulgaria', iso2: 'BG', dialCode: '+359', minLength: 8, maxLength: 9 },
  { name: 'Burkina Faso', iso2: 'BF', dialCode: '+226', minLength: 8, maxLength: 8 },
  { name: 'Burundi', iso2: 'BI', dialCode: '+257', minLength: 8, maxLength: 8 },
  { name: 'Cambodia', iso2: 'KH', dialCode: '+855', minLength: 8, maxLength: 9 },
  { name: 'Cameroon', iso2: 'CM', dialCode: '+237', minLength: 9, maxLength: 9 },
  { name: 'Canada', iso2: 'CA', dialCode: '+1', minLength: 10, maxLength: 10 },
  { name: 'Cape Verde', iso2: 'CV', dialCode: '+238', minLength: 7, maxLength: 7 },
  { name: 'Cayman Islands', iso2: 'KY', dialCode: '+1345', minLength: 10, maxLength: 10 },
  { name: 'Central African Republic', iso2: 'CF', dialCode: '+236', minLength: 8, maxLength: 8 },
  { name: 'Chad', iso2: 'TD', dialCode: '+235', minLength: 8, maxLength: 8 },
  { name: 'Chile', iso2: 'CL', dialCode: '+56', minLength: 9, maxLength: 9 },
  { name: 'China', iso2: 'CN', dialCode: '+86', minLength: 11, maxLength: 11 },
  { name: 'Colombia', iso2: 'CO', dialCode: '+57', minLength: 10, maxLength: 10 },
  { name: 'Comoros', iso2: 'KM', dialCode: '+269', minLength: 7, maxLength: 7 },
  { name: 'Congo', iso2: 'CG', dialCode: '+242', minLength: 9, maxLength: 9 },
  { name: 'Costa Rica', iso2: 'CR', dialCode: '+506', minLength: 8, maxLength: 8 },
  { name: 'Croatia', iso2: 'HR', dialCode: '+385', minLength: 8, maxLength: 9 },
  { name: 'Cuba', iso2: 'CU', dialCode: '+53', minLength: 8, maxLength: 8 },
  { name: 'Curacao', iso2: 'CW', dialCode: '+599', minLength: 7, maxLength: 8 },
  { name: 'Cyprus', iso2: 'CY', dialCode: '+357', minLength: 8, maxLength: 8 },
  { name: 'Czech Republic', iso2: 'CZ', dialCode: '+420', minLength: 9, maxLength: 9 },
  { name: 'Democratic Republic of the Congo', iso2: 'CD', dialCode: '+243', minLength: 9, maxLength: 9 },
  { name: 'Denmark', iso2: 'DK', dialCode: '+45', minLength: 8, maxLength: 8 },
  { name: 'Djibouti', iso2: 'DJ', dialCode: '+253', minLength: 8, maxLength: 8 },
  { name: 'Dominica', iso2: 'DM', dialCode: '+1767', minLength: 10, maxLength: 10 },
  { name: 'Dominican Republic', iso2: 'DO', dialCode: '+1809', minLength: 10, maxLength: 10 },
  { name: 'Ecuador', iso2: 'EC', dialCode: '+593', minLength: 8, maxLength: 9 },
  { name: 'Egypt', iso2: 'EG', dialCode: '+20', minLength: 10, maxLength: 10 },
  { name: 'El Salvador', iso2: 'SV', dialCode: '+503', minLength: 8, maxLength: 8 },
  { name: 'Equatorial Guinea', iso2: 'GQ', dialCode: '+240', minLength: 9, maxLength: 9 },
  { name: 'Eritrea', iso2: 'ER', dialCode: '+291', minLength: 7, maxLength: 7 },
  { name: 'Estonia', iso2: 'EE', dialCode: '+372', minLength: 7, maxLength: 10 },
  { name: 'Eswatini', iso2: 'SZ', dialCode: '+268', minLength: 8, maxLength: 8 },
  { name: 'Ethiopia', iso2: 'ET', dialCode: '+251', minLength: 9, maxLength: 9 },
  { name: 'Fiji', iso2: 'FJ', dialCode: '+679', minLength: 7, maxLength: 7 },
  { name: 'Finland', iso2: 'FI', dialCode: '+358', minLength: 7, maxLength: 12 },
  { name: 'France', iso2: 'FR', dialCode: '+33', minLength: 9, maxLength: 9 },
  { name: 'French Guiana', iso2: 'GF', dialCode: '+594', minLength: 9, maxLength: 9 },
  { name: 'French Polynesia', iso2: 'PF', dialCode: '+689', minLength: 8, maxLength: 8 },
  { name: 'Gabon', iso2: 'GA', dialCode: '+241', minLength: 8, maxLength: 9 },
  { name: 'Gambia', iso2: 'GM', dialCode: '+220', minLength: 7, maxLength: 7 },
  { name: 'Georgia', iso2: 'GE', dialCode: '+995', minLength: 9, maxLength: 9 },
  { name: 'Germany', iso2: 'DE', dialCode: '+49', minLength: 7, maxLength: 13 },
  { name: 'Ghana', iso2: 'GH', dialCode: '+233', minLength: 9, maxLength: 9 },
  { name: 'Gibraltar', iso2: 'GI', dialCode: '+350', minLength: 8, maxLength: 8 },
  { name: 'Greece', iso2: 'GR', dialCode: '+30', minLength: 10, maxLength: 10 },
  { name: 'Greenland', iso2: 'GL', dialCode: '+299', minLength: 6, maxLength: 6 },
  { name: 'Grenada', iso2: 'GD', dialCode: '+1473', minLength: 10, maxLength: 10 },
  { name: 'Guadeloupe', iso2: 'GP', dialCode: '+590', minLength: 9, maxLength: 9 },
  { name: 'Guam', iso2: 'GU', dialCode: '+1671', minLength: 10, maxLength: 10 },
  { name: 'Guatemala', iso2: 'GT', dialCode: '+502', minLength: 8, maxLength: 8 },
  { name: 'Guinea', iso2: 'GN', dialCode: '+224', minLength: 9, maxLength: 9 },
  { name: 'Guinea-Bissau', iso2: 'GW', dialCode: '+245', minLength: 7, maxLength: 7 },
  { name: 'Guyana', iso2: 'GY', dialCode: '+592', minLength: 7, maxLength: 7 },
  { name: 'Haiti', iso2: 'HT', dialCode: '+509', minLength: 8, maxLength: 8 },
  { name: 'Honduras', iso2: 'HN', dialCode: '+504', minLength: 8, maxLength: 8 },
  { name: 'Hong Kong', iso2: 'HK', dialCode: '+852', minLength: 8, maxLength: 8 },
  { name: 'Hungary', iso2: 'HU', dialCode: '+36', minLength: 8, maxLength: 9 },
  { name: 'Iceland', iso2: 'IS', dialCode: '+354', minLength: 7, maxLength: 9 },
  { name: 'India', iso2: 'IN', dialCode: '+91', minLength: 10, maxLength: 10 },
  { name: 'Indonesia', iso2: 'ID', dialCode: '+62', minLength: 9, maxLength: 12 },
  { name: 'Iran', iso2: 'IR', dialCode: '+98', minLength: 10, maxLength: 10 },
  { name: 'Iraq', iso2: 'IQ', dialCode: '+964', minLength: 10, maxLength: 10 },
  { name: 'Ireland', iso2: 'IE', dialCode: '+353', minLength: 7, maxLength: 9 },
  { name: 'Israel', iso2: 'IL', dialCode: '+972', minLength: 8, maxLength: 9 },
  { name: 'Italy', iso2: 'IT', dialCode: '+39', minLength: 6, maxLength: 11 },
  { name: 'Ivory Coast', iso2: 'CI', dialCode: '+225', minLength: 10, maxLength: 10 },
  { name: 'Jamaica', iso2: 'JM', dialCode: '+1876', minLength: 10, maxLength: 10 },
  { name: 'Japan', iso2: 'JP', dialCode: '+81', minLength: 10, maxLength: 10 },
  { name: 'Jordan', iso2: 'JO', dialCode: '+962', minLength: 8, maxLength: 9 },
  { name: 'Kazakhstan', iso2: 'KZ', dialCode: '+7', minLength: 10, maxLength: 10 },
  { name: 'Kenya', iso2: 'KE', dialCode: '+254', minLength: 9, maxLength: 9 },
  { name: 'Kiribati', iso2: 'KI', dialCode: '+686', minLength: 5, maxLength: 8 },
  { name: 'Kosovo', iso2: 'XK', dialCode: '+383', minLength: 8, maxLength: 8 },
  { name: 'Kuwait', iso2: 'KW', dialCode: '+965', minLength: 8, maxLength: 8 },
  { name: 'Kyrgyzstan', iso2: 'KG', dialCode: '+996', minLength: 9, maxLength: 9 },
  { name: 'Laos', iso2: 'LA', dialCode: '+856', minLength: 8, maxLength: 10 },
  { name: 'Latvia', iso2: 'LV', dialCode: '+371', minLength: 8, maxLength: 8 },
  { name: 'Lebanon', iso2: 'LB', dialCode: '+961', minLength: 7, maxLength: 8 },
  { name: 'Lesotho', iso2: 'LS', dialCode: '+266', minLength: 8, maxLength: 8 },
  { name: 'Liberia', iso2: 'LR', dialCode: '+231', minLength: 7, maxLength: 8 },
  { name: 'Libya', iso2: 'LY', dialCode: '+218', minLength: 9, maxLength: 9 },
  { name: 'Liechtenstein', iso2: 'LI', dialCode: '+423', minLength: 7, maxLength: 9 },
  { name: 'Lithuania', iso2: 'LT', dialCode: '+370', minLength: 8, maxLength: 8 },
  { name: 'Luxembourg', iso2: 'LU', dialCode: '+352', minLength: 6, maxLength: 11 },
  { name: 'Macau', iso2: 'MO', dialCode: '+853', minLength: 8, maxLength: 8 },
  { name: 'Madagascar', iso2: 'MG', dialCode: '+261', minLength: 9, maxLength: 9 },
  { name: 'Malawi', iso2: 'MW', dialCode: '+265', minLength: 7, maxLength: 9 },
  { name: 'Malaysia', iso2: 'MY', dialCode: '+60', minLength: 8, maxLength: 10 },
  { name: 'Maldives', iso2: 'MV', dialCode: '+960', minLength: 7, maxLength: 7 },
  { name: 'Mali', iso2: 'ML', dialCode: '+223', minLength: 8, maxLength: 8 },
  { name: 'Malta', iso2: 'MT', dialCode: '+356', minLength: 8, maxLength: 8 },
  { name: 'Marshall Islands', iso2: 'MH', dialCode: '+692', minLength: 7, maxLength: 7 },
  { name: 'Martinique', iso2: 'MQ', dialCode: '+596', minLength: 9, maxLength: 9 },
  { name: 'Mauritania', iso2: 'MR', dialCode: '+222', minLength: 8, maxLength: 8 },
  { name: 'Mauritius', iso2: 'MU', dialCode: '+230', minLength: 7, maxLength: 8 },
  { name: 'Mexico', iso2: 'MX', dialCode: '+52', minLength: 10, maxLength: 10 },
  { name: 'Micronesia', iso2: 'FM', dialCode: '+691', minLength: 7, maxLength: 7 },
  { name: 'Moldova', iso2: 'MD', dialCode: '+373', minLength: 8, maxLength: 8 },
  { name: 'Monaco', iso2: 'MC', dialCode: '+377', minLength: 5, maxLength: 9 },
  { name: 'Mongolia', iso2: 'MN', dialCode: '+976', minLength: 8, maxLength: 8 },
  { name: 'Montenegro', iso2: 'ME', dialCode: '+382', minLength: 8, maxLength: 8 },
  { name: 'Montserrat', iso2: 'MS', dialCode: '+1664', minLength: 10, maxLength: 10 },
  { name: 'Morocco', iso2: 'MA', dialCode: '+212', minLength: 9, maxLength: 9 },
  { name: 'Mozambique', iso2: 'MZ', dialCode: '+258', minLength: 8, maxLength: 9 },
  { name: 'Myanmar', iso2: 'MM', dialCode: '+95', minLength: 8, maxLength: 10 },
  { name: 'Namibia', iso2: 'NA', dialCode: '+264', minLength: 7, maxLength: 9 },
  { name: 'Nauru', iso2: 'NR', dialCode: '+674', minLength: 7, maxLength: 7 },
  { name: 'Nepal', iso2: 'NP', dialCode: '+977', minLength: 10, maxLength: 10 },
  { name: 'Netherlands', iso2: 'NL', dialCode: '+31', minLength: 9, maxLength: 9 },
  { name: 'New Caledonia', iso2: 'NC', dialCode: '+687', minLength: 6, maxLength: 6 },
  { name: 'New Zealand', iso2: 'NZ', dialCode: '+64', minLength: 8, maxLength: 10 },
  { name: 'Nicaragua', iso2: 'NI', dialCode: '+505', minLength: 8, maxLength: 8 },
  { name: 'Niger', iso2: 'NE', dialCode: '+227', minLength: 8, maxLength: 8 },
  { name: 'Nigeria', iso2: 'NG', dialCode: '+234', minLength: 10, maxLength: 10 },
  { name: 'North Macedonia', iso2: 'MK', dialCode: '+389', minLength: 8, maxLength: 8 },
  { name: 'Northern Mariana Islands', iso2: 'MP', dialCode: '+1670', minLength: 10, maxLength: 10 },
  { name: 'Norway', iso2: 'NO', dialCode: '+47', minLength: 8, maxLength: 8 },
  { name: 'Oman', iso2: 'OM', dialCode: '+968', minLength: 8, maxLength: 8 },
  { name: 'Pakistan', iso2: 'PK', dialCode: '+92', minLength: 10, maxLength: 10 },
  { name: 'Palau', iso2: 'PW', dialCode: '+680', minLength: 7, maxLength: 7 },
  { name: 'Palestine', iso2: 'PS', dialCode: '+970', minLength: 8, maxLength: 9 },
  { name: 'Panama', iso2: 'PA', dialCode: '+507', minLength: 7, maxLength: 8 },
  { name: 'Papua New Guinea', iso2: 'PG', dialCode: '+675', minLength: 7, maxLength: 8 },
  { name: 'Paraguay', iso2: 'PY', dialCode: '+595', minLength: 9, maxLength: 9 },
  { name: 'Peru', iso2: 'PE', dialCode: '+51', minLength: 9, maxLength: 9 },
  { name: 'Philippines', iso2: 'PH', dialCode: '+63', minLength: 10, maxLength: 10 },
  { name: 'Poland', iso2: 'PL', dialCode: '+48', minLength: 9, maxLength: 9 },
  { name: 'Portugal', iso2: 'PT', dialCode: '+351', minLength: 9, maxLength: 9 },
  { name: 'Puerto Rico', iso2: 'PR', dialCode: '+1787', minLength: 10, maxLength: 10 },
  { name: 'Qatar', iso2: 'QA', dialCode: '+974', minLength: 8, maxLength: 8 },
  { name: 'Reunion', iso2: 'RE', dialCode: '+262', minLength: 9, maxLength: 9 },
  { name: 'Romania', iso2: 'RO', dialCode: '+40', minLength: 9, maxLength: 9 },
  { name: 'Russia', iso2: 'RU', dialCode: '+7', minLength: 10, maxLength: 10 },
  { name: 'Rwanda', iso2: 'RW', dialCode: '+250', minLength: 9, maxLength: 9 },
  { name: 'Saint Kitts and Nevis', iso2: 'KN', dialCode: '+1869', minLength: 10, maxLength: 10 },
  { name: 'Saint Lucia', iso2: 'LC', dialCode: '+1758', minLength: 10, maxLength: 10 },
  { name: 'Saint Vincent and the Grenadines', iso2: 'VC', dialCode: '+1784', minLength: 10, maxLength: 10 },
  { name: 'Samoa', iso2: 'WS', dialCode: '+685', minLength: 5, maxLength: 7 },
  { name: 'San Marino', iso2: 'SM', dialCode: '+378', minLength: 6, maxLength: 10 },
  { name: 'Sao Tome and Principe', iso2: 'ST', dialCode: '+239', minLength: 7, maxLength: 7 },
  { name: 'Saudi Arabia', iso2: 'SA', dialCode: '+966', minLength: 9, maxLength: 9 },
  { name: 'Senegal', iso2: 'SN', dialCode: '+221', minLength: 9, maxLength: 9 },
  { name: 'Serbia', iso2: 'RS', dialCode: '+381', minLength: 8, maxLength: 9 },
  { name: 'Seychelles', iso2: 'SC', dialCode: '+248', minLength: 7, maxLength: 7 },
  { name: 'Sierra Leone', iso2: 'SL', dialCode: '+232', minLength: 8, maxLength: 8 },
  { name: 'Singapore', iso2: 'SG', dialCode: '+65', minLength: 8, maxLength: 8 },
  { name: 'Sint Maarten', iso2: 'SX', dialCode: '+1721', minLength: 10, maxLength: 10 },
  { name: 'Slovakia', iso2: 'SK', dialCode: '+421', minLength: 9, maxLength: 9 },
  { name: 'Slovenia', iso2: 'SI', dialCode: '+386', minLength: 8, maxLength: 8 },
  { name: 'Solomon Islands', iso2: 'SB', dialCode: '+677', minLength: 5, maxLength: 7 },
  { name: 'Somalia', iso2: 'SO', dialCode: '+252', minLength: 7, maxLength: 9 },
  { name: 'South Africa', iso2: 'ZA', dialCode: '+27', minLength: 9, maxLength: 9 },
  { name: 'South Korea', iso2: 'KR', dialCode: '+82', minLength: 9, maxLength: 10 },
  { name: 'South Sudan', iso2: 'SS', dialCode: '+211', minLength: 9, maxLength: 9 },
  { name: 'Spain', iso2: 'ES', dialCode: '+34', minLength: 9, maxLength: 9 },
  { name: 'Sri Lanka', iso2: 'LK', dialCode: '+94', minLength: 9, maxLength: 9 },
  { name: 'Sudan', iso2: 'SD', dialCode: '+249', minLength: 9, maxLength: 9 },
  { name: 'Suriname', iso2: 'SR', dialCode: '+597', minLength: 6, maxLength: 7 },
  { name: 'Sweden', iso2: 'SE', dialCode: '+46', minLength: 7, maxLength: 10 },
  { name: 'Switzerland', iso2: 'CH', dialCode: '+41', minLength: 9, maxLength: 9 },
  { name: 'Syria', iso2: 'SY', dialCode: '+963', minLength: 8, maxLength: 9 },
  { name: 'Taiwan', iso2: 'TW', dialCode: '+886', minLength: 9, maxLength: 9 },
  { name: 'Tajikistan', iso2: 'TJ', dialCode: '+992', minLength: 9, maxLength: 9 },
  { name: 'Tanzania', iso2: 'TZ', dialCode: '+255', minLength: 9, maxLength: 9 },
  { name: 'Thailand', iso2: 'TH', dialCode: '+66', minLength: 8, maxLength: 9 },
  { name: 'Timor-Leste', iso2: 'TL', dialCode: '+670', minLength: 7, maxLength: 8 },
  { name: 'Togo', iso2: 'TG', dialCode: '+228', minLength: 8, maxLength: 8 },
  { name: 'Tonga', iso2: 'TO', dialCode: '+676', minLength: 5, maxLength: 7 },
  { name: 'Trinidad and Tobago', iso2: 'TT', dialCode: '+1868', minLength: 10, maxLength: 10 },
  { name: 'Tunisia', iso2: 'TN', dialCode: '+216', minLength: 8, maxLength: 8 },
  { name: 'Turkey', iso2: 'TR', dialCode: '+90', minLength: 10, maxLength: 10 },
  { name: 'Turkmenistan', iso2: 'TM', dialCode: '+993', minLength: 8, maxLength: 8 },
  { name: 'Turks and Caicos Islands', iso2: 'TC', dialCode: '+1649', minLength: 10, maxLength: 10 },
  { name: 'Tuvalu', iso2: 'TV', dialCode: '+688', minLength: 5, maxLength: 6 },
  { name: 'Uganda', iso2: 'UG', dialCode: '+256', minLength: 9, maxLength: 9 },
  { name: 'Ukraine', iso2: 'UA', dialCode: '+380', minLength: 9, maxLength: 9 },
  { name: 'United Arab Emirates', iso2: 'AE', dialCode: '+971', minLength: 8, maxLength: 9 },
  { name: 'United Kingdom', iso2: 'GB', dialCode: '+44', minLength: 10, maxLength: 10 },
  { name: 'United States', iso2: 'US', dialCode: '+1', minLength: 10, maxLength: 10 },
  { name: 'Uruguay', iso2: 'UY', dialCode: '+598', minLength: 8, maxLength: 8 },
  { name: 'Uzbekistan', iso2: 'UZ', dialCode: '+998', minLength: 9, maxLength: 9 },
  { name: 'Vanuatu', iso2: 'VU', dialCode: '+678', minLength: 5, maxLength: 7 },
  { name: 'Vatican City', iso2: 'VA', dialCode: '+39', minLength: 6, maxLength: 11 },
  { name: 'Venezuela', iso2: 'VE', dialCode: '+58', minLength: 10, maxLength: 10 },
  { name: 'Vietnam', iso2: 'VN', dialCode: '+84', minLength: 9, maxLength: 10 },
  { name: 'Yemen', iso2: 'YE', dialCode: '+967', minLength: 7, maxLength: 9 },
  { name: 'Zambia', iso2: 'ZM', dialCode: '+260', minLength: 9, maxLength: 9 },
  { name: 'Zimbabwe', iso2: 'ZW', dialCode: '+263', minLength: 9, maxLength: 9 },
]

export const defaultPhoneCountry = phoneCountries.find((country) => country.iso2 === 'KE') || phoneCountries[0]

export const normalizeNationalNumber = (value: string) => value.replace(/\D/g, '').replace(/^0+/, '')

export const buildE164PhoneNumber = (dialCode: string, nationalNumber: string) => {
  const digits = normalizeNationalNumber(nationalNumber)
  return digits ? `${dialCode}${digits}` : ''
}

export const isValidPhoneForCountry = (country: PhoneCountry, nationalNumber: string) => {
  const digits = normalizeNationalNumber(nationalNumber)
  return digits.length >= country.minLength && digits.length <= country.maxLength
}

export const findCountryByPhoneNumber = (value: string) => {
  const compactValue = value.replace(/[^\d+]/g, '')
  return phoneCountries
    .filter((country) => compactValue.startsWith(country.dialCode))
    .sort((a, b) => b.dialCode.length - a.dialCode.length)[0]
}

export const isValidE164PhoneNumber = (value: string) => {
  if (!/^\+[1-9]\d{7,14}$/.test(value)) return false

  const country = findCountryByPhoneNumber(value)
  if (!country) return false

  const nationalNumber = value.slice(country.dialCode.length)
  return isValidPhoneForCountry(country, nationalNumber)
}
